services:
  terraform-ui:
    build:
      context: .
      args:
        TF_VERSION: "1.9.5"
    ports:
      - "8080:8080"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - TF_PLUGIN_CACHE_DIR=/root/.terraform.d/plugin-cache
      # Optional: protect /.logs with a token (your app supports this)
      - TFUI_LOGS_TOKEN=${TFUI_LOGS_TOKEN:-}
    volumes:
      # Persist Terraform state/configs
      - ./terraform:/app/terraform
      # Speed up provider downloads between runs
      - tf_plugin_cache:/root/.terraform.d/plugin-cache
      # Optional: live edit app.py without rebuild
      # - ./app.py:/app/app.py:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/status >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

volumes:
  tf_plugin_cache:

